# Generated by Django 3.2 on 2022-02-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bvn',
            field=models.IntegerField(default=20),
        ),
    ]
